trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
      - README.md
      - LICENSE
      - .github
stages:

- stage: umiBundleTest
  variables:
    - group: umiVariableGroup
  jobs:
  - job: onReleaseJob
    pool:
      name: umiPoolName 
      demands:
        - agent.name -equals agentumitest
    steps:
    - script: env | sort
      displayName: 'Environment / Context'
    
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: 3.10.12

    - script: |
        echo "Logging in with Managed Identity..."
        az login --identity -u $(MANAGED_IDENTITY_CLIENT_ID)
      displayName: 'Azure CLI Login with Managed Identity'

    - script: |
        echo Env Variables configuration...
        
      env:
        DATABRICKS_HOST: $(DATABRICKS_HOST)
        DATABRICKS_AZURE_USE_MSI : 'true'
      displayName: 'Configurar CLI do Databricks'
        

    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - script: |
            # this is because of the old dependency inside Nutter
            python -m pip install --upgrade pip nutter
            python -m pip install wheel
            python -m pip install setuptools
      displayName: 'Install dependencies' 
      
    - script: |
        databricks bundle validate -t $(env)
      displayName: Validate bundle for $(env) enviroment

    - script: |
        echo Deploy do bundle via CLI do Databricks...
        databricks bundle deploy -t $(env) --force-lock
      displayName: Deploy job on $(env) enviroment

    

      
    
        
    
