trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
      - README.md
      - LICENSE
      - .github
stages:

- stage: umiBundleTest
  variables:
    - group: umiVariableGroup
  jobs:
  - job: onReleaseJob
    pool:
      name: testGaneshMachine
      demands:
        - agent.name -equals devvmalfeu
    steps:
    - script: env | sort
      displayName: 'Environment / Context'
    
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: 3.10.12

    - script: |
        echo "Logging in with Managed Identity..."
        az login --identity -u $(MANAGED_IDENTITY_CLIENT_ID)
      displayName: 'Azure CLI Login with Managed Identity'

    - script: |
        echo "Getting the Databricks access token..."
        DATABRICKS_TOKEN=$(az account get-access-token --resource "2ff814a6-3304-4ab8-85cb-cd0e6f879c1d" --query "accessToken" -o tsv)
        echo "##vso[task.setvariable variable=DATABRICKS_TOKEN;issecret=true]$DATABRICKS_TOKEN"
      displayName: 'Getting the Databricks token'


    - script: |
        echo Configurando o CLI do Databricks...
        echo -e "$(DATABRICKS_HOST)\n$(DATABRICKS_TOKEN)" | databricks configure --token
      env:
        DATABRICKS_HOST: $(DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
        DATABRICKS_AZURE_USE_MSI : 'true'
      displayName: 'Configurar CLI do Databricks'
        

    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - script: |
            # this is because of the old dependency inside Nutter
            python -m pip install --upgrade pip nutter
            python -m pip install wheel
            python -m pip install setuptools
      displayName: 'Install dependencies' 
      
    - script: |
        echo Configurando o CLI do Databricks...
        databricks configure --token
        echo -e "[DATABRICKS_HOST]\n[DATABRICKS_TOKEN]" | databricks configure --token
      env:
        DATABRICKS_HOST: $(DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
      displayName: 'Configurar CLI do Databricks'
    - script: |
        databricks bundle validate -t $(env)
      displayName: Validate bundle for $(env) enviroment

    - script: |
        echo Deploy do bundle via CLI do Databricks...
        databricks bundle deploy -t $(env) --force-lock
      displayName: Deploy job on $(env) enviroment

    

      
    
        
    
